default: &default
  adapter: postgresql
  pool: 5

development:
  adapter: postgresql
  <<: *default
  database: bravado_quest_development
  host: ''
  port: 5432
  pool: 25

test:
  adapter: postgresql
  <<: *default
  database: bravado_quest_test

production:
  <<: *default
  url:  <%= ENV["DATABASE_URL"] %>
  pool: 50

